// Tokens para inyección de dependencias de repositorios
export const ADMISSION_STAGE_REPOSITORY = 'ADMISSION_STAGE_REPOSITORY';
export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
export const CHARGE_REPOSITORY = 'CHARGE_REPOSITORY';
export const COMMUNICATION_REPOSITORY = 'COMMUNICATION_REPOSITORY';
export const COURSE_REPOSITORY = 'COURSE_REPOSITORY';
export const ENROLLMENT_REPOSITORY = 'ENROLLMENT_REPOSITORY';
export const EVALUATION_RESULT_REPOSITORY = 'EVALUATION_RESULT_REPOSITORY';
export const GUARDIAN_REPOSITORY = 'GUARDIAN_REPOSITORY';
export const PROSPECT_INTERACTION_REPOSITORY =
  'PROSPECT_INTERACTION_REPOSITORY';
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const PROSPECT_REPOSITORY = 'PROSPECT_REPOSITORY';
export const SCHEDULE_REPOSITORY = 'SCHEDULE_REPOSITORY';
export const SECTION_REPOSITORY = 'SECTION_REPOSITORY';
export const STUDENT_REPOSITORY = 'STUDENT_REPOSITORY';
export const TARIFF_REPOSITORY = 'TARIFF_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
