#!/usr/bin/env sh
set -e

CHANGED="$(git diff --cached --name-only)"

if printf '%s\n' "$CHANGED" | rg -q '^backend/'; then
  sh backend/.husky/pre-commit
fi

if printf '%s\n' "$CHANGED" | rg -q '^prototype/'; then
  sh prototype/.husky/pre-commit
fi

