import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  HttpStatus,
  Logger,
} from '@nestjs/common';
import { Request, Response } from 'express';
import { Prisma } from '@prisma/client';
import { BaseErrorResponse } from '../../config/interfaces/base-error-response';
import { DomainException } from '../../domain/exceptions/base/domain-exception';

@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
  private readonly logger = new Logger(HttpExceptionFilter.name);

  catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();

    let status = HttpStatus.INTERNAL_SERVER_ERROR;
    let message = 'Internal Server Error';
    let errorDetails: string | string[] | undefined = undefined;

    if (exception instanceof HttpException) {
      status = exception.getStatus();
      const resBody = exception.getResponse();

      if (typeof resBody === 'object' && resBody !== null) {
        const bodyObj = resBody as any;
        message = Array.isArray(bodyObj.message)
          ? bodyObj.message.join(', ')
          : bodyObj.message || exception.message;
        errorDetails = bodyObj.message; // Contains precise validation arrays if generated by ValidationPipe
      } else {
        message = typeof resBody === 'string' ? resBody : exception.message;
      }
    } else if (exception instanceof DomainException) {
      switch (exception.code) {
        case 'USER_NOT_FOUND':
          status = HttpStatus.NOT_FOUND;
          break;
        case 'EMAIL_ALREADY_EXISTS':
          status = HttpStatus.CONFLICT;
          break;
        default:
          status = HttpStatus.BAD_REQUEST;
          break;
      }
      message = exception.message;
      errorDetails = exception.code;
    } else if (exception instanceof Prisma.PrismaClientKnownRequestError) {
      // Prisma unique constraints and index error translations
      switch (exception.code) {
        case 'P2002':
          status = HttpStatus.CONFLICT;
          message =
            'Violación de restricción única: ya existe un registro con estos datos.';
          errorDetails = exception.meta as any;
          break;
        case 'P2025':
          status = HttpStatus.NOT_FOUND;
          message = 'El registro solicitado no existe o no fue encontrado.';
          break;
        default:
          status = HttpStatus.BAD_REQUEST;
          message = `Error de base de datos (Prisma ${exception.code})`;
          break;
      }
      this.logger.warn(
        `Prisma Error [${exception.code}]: ${exception.message}`,
      );
    } else if (exception instanceof Error) {
      message = exception.message;
      this.logger.error(
        `💥 Unhandled Exception: ${exception.message}`,
        exception.stack,
      );
    } else {
      this.logger.error(`💥 Unknown Exception: ${JSON.stringify(exception)}`);
    }

    const errorResponse: BaseErrorResponse = {
      statusCode: status,
      message,
      error: errorDetails,
      timestamp: new Date().toISOString(),
      path: request.url,
    };

    response.status(status).json(errorResponse);
  }
}
